(function(){
'use strict';Object.freeze({esVersion:6,assumingES6:!0,productionMode:!0,linkerVersion:"1.10.1",fileLevelThis:this});var e;function aa(a){for(var b in a)return b}
function k(a){switch(typeof a){case "string":return"java.lang.String";case "number":return"number"===typeof a&&(a|0)===a&&1/a!==1/-0?a<<24>>24===a?"java.lang.Byte":a<<16>>16===a?"java.lang.Short":"java.lang.Integer":"number"!==typeof a||a===a&&Math.fround(a)!==a?"java.lang.Double":"java.lang.Float";case "boolean":return"java.lang.Boolean";case "undefined":return"java.lang.Void";default:return null===a?a.M():a instanceof m?"java.lang.Long":a&&a.$classData?a.$classData.name:null.N()}}var n=0,p=new WeakMap;
function ba(a){switch(typeof a){case "string":return q(a);case "number":a=+a;r||(r=new t);var b=r;var c=a|0;c===a&&-Infinity!==1/a?a=c:(b.A[0]=a,a=(b.v[0]|0)^(b.v[1]|0));return a;case "bigint":b=0;for(a<BigInt(0)&&(a=~a);a!==BigInt(0);)b^=Number(BigInt.asIntN(32,a)),a>>=BigInt(32);return b;case "boolean":return a?1231:1237;case "undefined":return 0;case "symbol":return a=a.description,void 0===a?0:q(a);default:if(null===a)return 0;b=p.get(a);void 0===b&&(n=b=n+1|0,p.set(a,b));return b}}
function u(){}u.prototype.constructor=u;function v(){}v.prototype=u.prototype;u.prototype.u=function(){return ba(this)};u.prototype.n=function(){var a=this.u();return k(this)+"@"+(+(a>>>0)).toString(16)};u.prototype.toString=function(){return this.n()};function w(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=null}else this.a=a}w.prototype=new v;w.prototype.constructor=w;function x(){}x.prototype=w.prototype;
function y(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=!1}else this.a=a}y.prototype=new v;y.prototype.constructor=y;function z(a){this.a="number"===typeof a?new Uint16Array(a):a}z.prototype=new v;z.prototype.constructor=z;function A(a){this.a="number"===typeof a?new Int8Array(a):a}A.prototype=new v;A.prototype.constructor=A;function C(a){this.a="number"===typeof a?new Int16Array(a):a}C.prototype=new v;C.prototype.constructor=C;
function D(a){this.a="number"===typeof a?new Int32Array(a):a}D.prototype=new v;D.prototype.constructor=D;function E(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=e}else this.a=a}E.prototype=new v;E.prototype.constructor=E;function F(a){this.a="number"===typeof a?new Float32Array(a):a}F.prototype=new v;F.prototype.constructor=F;function G(a){this.a="number"===typeof a?new Float64Array(a):a}G.prototype=new v;G.prototype.constructor=G;
function H(){this.w=void 0;this.k=this.d=null;this.l=0;this.B=null;this.e="";this.g=this.j=void 0;this.name="";this.isJSClass=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function I(a,b,c,d){var f=new H;f.d={};f.B=a;f.e=b;f.g=h=>h===f;f.name=c;f.isPrimitive=!0;f.isInstance=()=>!1;void 0!==d&&(f.j=J(f,d));return f}
function K(a,b,c,d){var f=new H,h=aa(a);f.d=c;f.e="L"+b+";";f.g=g=>!!g.d[h];f.name=b;f.isInterface=!1;f.isInstance=d||(g=>!!(g&&g.$classData&&g.$classData.d[h]));return f}function J(a,b,c){var d=new H;b.prototype.$classData=d;var f="["+a.e;d.w=b;d.d={c:1,H:1,t:1};d.k=a;d.l=1;d.e=f;d.name=f;d.isArrayClass=!0;d.g=c||(h=>d===h);d.isInstance=h=>h instanceof b;return d}
function ca(){function a(g){if("number"===typeof g){this.a=Array(g);for(var l=0;l<g;l++)this.a[l]=null}else this.a=g}var b=L,c=new H;a.prototype=new x;a.prototype.constructor=a;var d=b.k||b,f=b.l+1;a.prototype.$classData=c;b="["+b.e;c.w=a;c.d={c:1,H:1,t:1};c.k=d;c.l=f;c.e=b;c.name=b;c.isArrayClass=!0;var h=g=>{var l=g.l;return l===f?d.g(g.k):l>f&&d===M};c.g=h;c.isInstance=g=>{g=g&&g.$classData;return!!g&&(g===c||h(g))};return c}var M=new H;M.d={c:1};M.e="Ljava.lang.Object;";M.g=a=>!a.isPrimitive;
M.name="java.lang.Object";M.isInstance=a=>null!==a;M.j=J(M,w,a=>{var b=a.l;return 1===b?!a.k.isPrimitive:1<b});u.prototype.$classData=M;I(void 0,"V","void",void 0);I(!1,"Z","boolean",y);I(0,"C","char",z);I(0,"B","byte",A);I(0,"S","short",C);I(0,"I","int",D);var ea=I(null,"J","long",E);I(0,"F","float",F);I(0,"D","double",G);function N(a,b){if(null===b)throw new O;b.h?b=b.i:(a=new P(a),b.i=a,b.h=!0,b=a);return b}function Q(){this.f="dark";this.s="light";this.b="hidden"}Q.prototype=new v;
Q.prototype.constructor=Q;function R(){S();return window.localStorage.getItem("theme")}function T(){S();document.documentElement.classList.add(S().f)}function U(){S();document.documentElement.classList.remove(S().f)}function V(a,b){U();b.o.classList.add(S().b);b.p.classList.add(S().b);b.q.classList.remove(S().b)}function fa(a,b){T();b.o.classList.add(S().b);b.p.classList.remove(S().b);b.q.classList.add(S().b)}
function W(a,b,c){b.o.classList.remove(S().b);b.p.classList.add(S().b);b.q.classList.add(S().b);c?T():U()}function ha(){S();var a=document.getElementById("mobile-navbar");document.getElementById("mobile-navbar-toggle").addEventListener("click",()=>!!a.classList.toggle(S().b))}
function ia(a,b){document.getElementById("theme-switch").addEventListener("click",()=>{var c=R();return null===c?(fa(S(),b),window.localStorage.setItem("theme",S().f),void 0):c===S().f?(V(S(),b),window.localStorage.setItem("theme",S().s),void 0):c===S().s?(b.r.matches?W(S(),b,!0):W(S(),b,!1),window.localStorage.removeItem("theme"),void 0):void 0})}function ja(a,b){b.r.addEventListener("change",c=>{null===R()&&(c.matches?W(S(),b,!0):W(S(),b,!1))})}
function ka(){S();var a=R(),b=window.matchMedia("(prefers-color-scheme: dark)");a===S().s?U():a===S().f?T():b.matches?T():U();document.addEventListener("DOMContentLoaded",()=>{ha();S();var c=new X;S();var d=c.h?c.i:N(b,c),f=R();f===S().s?V(S(),d):f===S().f?fa(S(),d):d.r.matches?W(S(),d,!0):W(S(),d,!1);ja(S(),c.h?c.i:N(b,c));ia(S(),c.h?c.i:N(b,c))})}Q.prototype.$classData=K({C:0},"com.laravelista.js.Main$package$",{C:1,c:1});var Y;function S(){Y||(Y=new Q);return Y}
function t(){this.A=this.v=this.m=null;r=this;this.m=new ArrayBuffer(8);this.v=new Int32Array(this.m,0,2);new Float32Array(this.m,0,2);this.A=new Float64Array(this.m,0,1);this.v[0]=16909060;new Int8Array(this.m,0,8)}t.prototype=new v;t.prototype.constructor=t;t.prototype.$classData=K({I:0},"java.lang.FloatingPointBits$",{I:1,c:1});var r;function m(a,b){this.z=a;this.y=b}m.prototype=new v;m.prototype.constructor=m;m.prototype.u=function(){return this.z^this.y};
m.prototype.n=function(){la||(la=new Z);var a=this.z,b=this.y;return b===a>>31?""+a:0>b?"-"+ma(-a|0,0!==a?~b:-b|0):ma(a,b)};m.prototype.$classData=K({E:0},"org.scalajs.linker.runtime.RuntimeLong",{E:1,c:1});
function ma(a,b){if(0===(-2097152&b))b=""+(4294967296*b+ +(a>>>0));else{var c=(32+Math.clz32(1E9)|0)-(0!==b?Math.clz32(b):32+Math.clz32(a)|0)|0,d=c,f=0===(32&d)?1E9<<d:0;d=0===(32&d)?5E8>>>(31-d|0)|0|0<<d:1E9<<d;var h=a,g=b;for(a=b=0;0<=c&&0!==(-2097152&g);){var l=h,B=g,na=f,da=d;if(B===da?(-2147483648^l)>=(-2147483648^na):(-2147483648^B)>=(-2147483648^da))l=g,B=d,g=h-f|0,l=(-2147483648^g)>(-2147483648^h)?-1+(l-B|0)|0:l-B|0,h=g,g=l,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;l=d>>>1|0;f=f>>>1|0|d<<31;d=l}c=g;if(0===
c?-1147483648<=(-2147483648^h):-2147483648<=(-2147483648^c))c=4294967296*g+ +(h>>>0),h=c/1E9,f=h/4294967296|0,d=b,b=h=d+(h|0)|0,a=(-2147483648^h)<(-2147483648^d)?1+(a+f|0)|0:a+f|0,h=c%1E9|0;c=""+h;b=""+(4294967296*a+ +(b>>>0))+"000000000".substring(c.length|0)+c}return b}function Z(){}Z.prototype=new v;Z.prototype.constructor=Z;Z.prototype.$classData=K({F:0},"org.scalajs.linker.runtime.RuntimeLong$",{F:1,c:1});var la;
function P(a){this.r=this.q=this.p=this.o=null;this.o=document.getElementById("theme-automatic");this.p=document.getElementById("theme-dark");this.q=document.getElementById("theme-light");this.r=a}P.prototype=new v;P.prototype.constructor=P;P.prototype.$classData=K({D:0},"com.laravelista.js.Main$package$Theme$2$",{D:1,c:1,L:1});
class oa extends Error{constructor(){super();this.x=null}n(){var a=k(this),b=this.x;return null===b?a:a+": "+b}u(){return u.prototype.u.call(this)}get message(){var a=this.x;return null===a?"":a}get name(){return k(this)}toString(){return this.n()}}function X(){this.h=!1;this.i=null}X.prototype=new v;X.prototype.constructor=X;X.prototype.n=function(){return"LazyRef "+(this.h?"of: "+this.i:"thunk")};X.prototype.$classData=K({K:0},"scala.runtime.LazyRef",{K:1,c:1,t:1});class pa extends oa{}
class qa extends pa{}class O extends qa{constructor(){super();this.x=null;"[object Error]"!==Object.prototype.toString.call(this)&&void 0!==Error.captureStackTrace&&Error.captureStackTrace(this)}}O.prototype.$classData=K({J:0},"java.lang.NullPointerException",{J:1,R:1,Q:1,S:1,c:1,t:1});function q(a){for(var b=0,c=1,d=-1+(a.length|0)|0;0<=d;)b=b+Math.imul(65535&(a.charCodeAt(d)|0),c)|0,c=Math.imul(31,c),d=-1+d|0;return b}
var L=K({G:0},"java.lang.String",{G:1,c:1,t:1,P:1,O:1,T:1,U:1},a=>"string"===typeof a);e=new m(0,0);ea.B=e;L.j||(L.j=ca());new L.j.w([]);try{ka()}catch(a){throw a;};
}).call(this);
//# sourceMappingURL=main.js.map
