(function(){
'use strict';var h;function k(a){switch(typeof a){case "string":return"java.lang.String";case "number":return aa(a)?a<<24>>24===a?"java.lang.Byte":a<<16>>16===a?"java.lang.Short":"java.lang.Integer":ba(a)?"java.lang.Float":"java.lang.Double";case "boolean":return"java.lang.Boolean";case "undefined":return"java.lang.Void";default:return a instanceof l?"java.lang.Long":a&&a.$classData?a.$classData.name:null.V()}}var ca=0,da=new WeakMap;
function ea(a){switch(typeof a){case "string":return fa(a);case "number":n||(n=new p);var b=n;var c=a|0;c===a&&-Infinity!==1/a?a=c:(b.C[0]=a,a=(b.v[0]|0)^(b.v[1]|0));return a;case "bigint":b=0;for(a<BigInt(0)&&(a=~a);a!==BigInt(0);)b^=Number(BigInt.asIntN(32,a)),a>>=BigInt(32);return b;case "boolean":return a?1231:1237;case "undefined":return 0;case "symbol":return a=a.description,void 0===a?0:fa(a);default:if(null===a)return 0;b=da.get(a);void 0===b&&(ca=b=ca+1|0,da.set(a,b));return b}}
function aa(a){return"number"===typeof a&&(a|0)===a&&1/a!==1/-0}function ba(a){return"number"===typeof a&&(a!==a||Math.fround(a)===a)}function q(){}q.prototype.constructor=q;function r(){}r.prototype=q.prototype;q.prototype.u=function(){return ea(this)};q.prototype.j=function(){var a=this.u();return k(this)+"@"+(+(a>>>0)).toString(16)};q.prototype.toString=function(){return this.j()};function t(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=null}else this.a=a}
t.prototype=new r;t.prototype.constructor=t;function ha(){}ha.prototype=t.prototype;function u(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=!1}else this.a=a}u.prototype=new r;u.prototype.constructor=u;function v(a){this.a="number"===typeof a?new Uint16Array(a):a}v.prototype=new r;v.prototype.constructor=v;function w(a){this.a="number"===typeof a?new Int8Array(a):a}w.prototype=new r;w.prototype.constructor=w;function x(a){this.a="number"===typeof a?new Int16Array(a):a}
x.prototype=new r;x.prototype.constructor=x;function y(a){this.a="number"===typeof a?new Int32Array(a):a}y.prototype=new r;y.prototype.constructor=y;function z(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=h}else this.a=a}z.prototype=new r;z.prototype.constructor=z;function A(a){this.a="number"===typeof a?new Float32Array(a):a}A.prototype=new r;A.prototype.constructor=A;function B(a){this.a="number"===typeof a?new Float64Array(a):a}B.prototype=new r;
B.prototype.constructor=B;function D(){this.x=void 0;this.l=this.e=null;this.m=0;this.D=null;this.f="";this.g=this.k=void 0;this.name="";this.y=!1;this.n=void 0}function E(a,b,c,d){var e=new D;e.e={};e.D=a;e.f=b;e.g=g=>g===e;e.name=c;e.y=!0;e.n=()=>!1;void 0!==d&&(e.k=ia(e,d));return e}
function F(a,b,c,d){var e=new D,g=Object.getOwnPropertyNames(c)[0];e.e=c;e.f="L"+b+";";e.g=f=>!!f.e[g];e.name=b;e.n=d||(f=>!!(f&&f.$classData&&f.$classData.e[g]));"number"!==typeof a&&(a.prototype.$classData=e);return e}function ia(a,b,c){var d=new D;b.prototype.$classData=d;var e="["+a.f;d.x=b;d.e={I:1,b:1};d.l=a;d.m=1;d.f=e;d.name=e;d.g=c||(g=>d===g);d.n=g=>g instanceof b;return d}
function ja(){function a(f){if("number"===typeof f){this.a=Array(f);for(var m=0;m<f;m++)this.a[m]=null}else this.a=f}var b=G,c=new D;a.prototype=new ha;a.prototype.constructor=a;a.prototype.$classData=c;var d=b.l||b,e=b.m+1;b="["+b.f;c.x=a;c.e={I:1,b:1};c.l=d;c.m=e;c.f=b;c.name=b;var g=f=>{var m=f.m;return m===e?d.g(f.l):m>e&&d===H};c.g=g;c.n=f=>{f=f&&f.$classData;return!!f&&(f===c||g(f))};return c}var H=new D;H.e={};H.f="Ljava.lang.Object;";H.g=a=>!a.y;H.name="java.lang.Object";H.n=a=>null!==a;
H.k=ia(H,t,a=>{var b=a.m;return 1===b?!a.l.y:1<b});q.prototype.$classData=H;E(void 0,"V","void",void 0);E(!1,"Z","boolean",u);E(0,"C","char",v);E(0,"B","byte",w);E(0,"S","short",x);E(0,"I","int",y);var ka=E(null,"J","long",z);E(0,"F","float",A);E(0,"D","double",B);function la(a,b){if(null===a)throw new ma;a.h?a=a.i:(b=new I(b),a.i=b,a.h=!0,a=b);return a}function J(){}J.prototype=new r;J.prototype.constructor=J;function K(){L();return window.localStorage.getItem("theme")}
function M(){L();document.documentElement.classList.add("dark")}function N(){L();document.documentElement.classList.remove("dark")}function na(a,b){N();b.q.classList.add("hidden");b.r.classList.add("hidden");b.s.classList.remove("hidden")}function oa(a,b){M();b.q.classList.add("hidden");b.r.classList.remove("hidden");b.s.classList.add("hidden")}function O(a,b,c){b.q.classList.remove("hidden");b.r.classList.add("hidden");b.s.classList.add("hidden");c?M():N()}
function pa(){L();var a=document.getElementById("mobile-navbar");document.getElementById("mobile-navbar-toggle").addEventListener("click",()=>!!a.classList.toggle("hidden"))}
function qa(a,b){document.getElementById("theme-switch").addEventListener("click",()=>{var c=K();return null===c?(oa(L(),b),window.localStorage.setItem("theme","dark"),void 0):"dark"===c?(na(L(),b),window.localStorage.setItem("theme","light"),void 0):"light"===c?(b.t.matches?O(L(),b,!0):O(L(),b,!1),window.localStorage.removeItem("theme"),void 0):void 0})}function sa(a,b){b.t.addEventListener("change",c=>{null===K()&&(c.matches?O(L(),b,!0):O(L(),b,!1))})}
function ta(){L();var a=K(),b=window.matchMedia("(prefers-color-scheme: dark)");"light"===a?N():"dark"===a?M():b.matches?M():N();document.addEventListener("DOMContentLoaded",()=>{pa();L();var c=new P;L();var d=c.h?c.i:la(c,b),e=K();"light"===e?na(L(),d):"dark"===e?oa(L(),d):d.t.matches?O(L(),d,!0):O(L(),d,!1);sa(L(),c.h?c.i:la(c,b));qa(L(),c.h?c.i:la(c,b))})}F(J,"com.laravelista.js.Main$package$",{N:1});var ua;function L(){ua||(ua=new J);return ua}
function p(){this.C=this.v=this.o=null;n=this;this.o=new ArrayBuffer(8);this.v=new Int32Array(this.o,0,2);new Float32Array(this.o,0,2);this.C=new Float64Array(this.o,0,1);this.v[0]=16909060;new Int8Array(this.o,0,8)}p.prototype=new r;p.prototype.constructor=p;F(p,"java.lang.FloatingPointBits$",{da:1});var n;function Q(){va=this}Q.prototype=new r;Q.prototype.constructor=Q;F(Q,"java.lang.System$Streams$",{ka:1});var va;F(0,"java.lang.Void",{la:1},a=>void 0===a);function l(a,b){this.B=a;this.A=b}
l.prototype=new r;l.prototype.constructor=l;l.prototype.u=function(){return this.B^this.A};l.prototype.j=function(){wa||(wa=new R);var a=this.B,b=this.A;return b===a>>31?""+a:0>b?"-"+xa(-a|0,0!==a?~b:-b|0):xa(a,b)};F(l,"org.scalajs.linker.runtime.RuntimeLong",{S:1});
function xa(a,b){if(0===(-2097152&b))b=""+(4294967296*b+ +(a>>>0));else{var c=(32+(Math.clz32(1E9)|0)|0)-(0!==b?Math.clz32(b)|0:32+(Math.clz32(a)|0)|0)|0,d=c,e=0===(32&d)?1E9<<d:0;d=0===(32&d)?5E8>>>(31-d|0)|0|0<<d:1E9<<d;var g=a,f=b;for(a=b=0;0<=c&&0!==(-2097152&f);){var m=g,C=f,Da=e,ra=d;if(C===ra?(-2147483648^m)>=(-2147483648^Da):(-2147483648^C)>=(-2147483648^ra))m=f,C=d,f=g-e|0,m=(-2147483648^f)>(-2147483648^g)?-1+(m-C|0)|0:m-C|0,g=f,f=m,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;m=d>>>1|0;e=e>>>1|0|d<<31;
d=m}c=f;if(0===c?-1147483648<=(-2147483648^g):-2147483648<=(-2147483648^c))c=4294967296*f+ +(g>>>0),g=c/1E9,e=g/4294967296|0,d=b,b=g=d+(g|0)|0,a=(-2147483648^g)<(-2147483648^d)?1+(a+e|0)|0:a+e|0,g=c%1E9|0;c=""+g;b=""+(4294967296*a+ +(b>>>0))+"000000000".substring(c.length)+c}return b}function R(){}R.prototype=new r;R.prototype.constructor=R;F(R,"org.scalajs.linker.runtime.RuntimeLong$",{T:1});var wa;function S(){}S.prototype=new r;S.prototype.constructor=S;F(S,"scala.util.CommandLineParser$",{oa:1});
function T(a){this.M=a}T.prototype=new r;T.prototype.constructor=T;T.prototype.j=function(){return"DynamicVariable("+this.M+")"};F(T,"scala.util.DynamicVariable",{pa:1});function I(a){this.t=this.s=this.r=this.q=null;this.q=document.getElementById("theme-automatic");this.r=document.getElementById("theme-dark");this.s=document.getElementById("theme-light");this.t=a}I.prototype=new r;I.prototype.constructor=I;F(I,"com.laravelista.js.Main$package$Theme$2$",{O:1,P:1});
function ya(a,b){a.z=b;"[object Error]"!==Object.prototype.toString.call(a)&&(void 0===Error.captureStackTrace||Object.isSealed(a)?Error():Error.captureStackTrace(a))}class za extends Error{constructor(){super();this.z=null}j(){var a=k(this),b=this.z;return null===b?a:a+": "+b}u(){return q.prototype.u.call(this)}get message(){var a=this.z;return null===a?"":a}get name(){return k(this)}toString(){return this.j()}}function U(){va||(va=new Q)}U.prototype=new r;U.prototype.constructor=U;
F(U,"scala.Console$",{ma:1,na:1});function P(){this.h=!1;this.i=null}P.prototype=new r;P.prototype.constructor=P;P.prototype.j=function(){return"LazyRef "+(this.h?"of: "+this.i:"thunk")};F(P,"scala.runtime.LazyRef",{qa:1,b:1});class Aa extends za{}function V(){}V.prototype=new r;V.prototype.constructor=V;function Ba(){}Ba.prototype=V.prototype;F(0,"java.lang.Boolean",{Y:1,b:1,c:1,d:1},a=>"boolean"===typeof a);F(0,"java.lang.Character",{aa:1,b:1,c:1,d:1},()=>!1);class Ca extends Aa{}
function W(){}W.prototype=new Ba;W.prototype.constructor=W;function Ea(){}Ea.prototype=W.prototype;class Fa extends Ca{constructor(a){super();ya(this,a)}}F(Fa,"java.lang.ArithmeticException",{X:1,K:1,J:1,L:1,b:1});F(0,"java.lang.Byte",{Z:1,p:1,b:1,c:1,d:1},a=>"number"===typeof a&&a<<24>>24===a&&1/a!==1/-0);function X(){}X.prototype=new Ba;X.prototype.constructor=X;F(X,"java.lang.JSConsoleBasedPrintStream$DummyOutputStream",{ga:1,G:1,E:1,H:1,F:1});
class ma extends Ca{constructor(){super();ya(this,null)}}F(ma,"java.lang.NullPointerException",{ia:1,K:1,J:1,L:1,b:1});F(0,"java.lang.Short",{ja:1,p:1,b:1,c:1,d:1},a=>"number"===typeof a&&a<<16>>16===a&&1/a!==1/-0);F(0,"java.lang.Double",{ba:1,p:1,b:1,c:1,d:1,w:1},a=>"number"===typeof a);F(0,"java.lang.Float",{ca:1,p:1,b:1,c:1,d:1,w:1},a=>ba(a));F(0,"java.lang.Integer",{ea:1,p:1,b:1,c:1,d:1,w:1},a=>aa(a));F(0,"java.lang.Long",{ha:1,p:1,b:1,c:1,d:1,w:1},a=>a instanceof l);
function fa(a){for(var b=0,c=1,d=-1+a.length|0;0<=d;)b=b+Math.imul(a.charCodeAt(d),c)|0,c=Math.imul(31,c),d=-1+d|0;return b}var G=F(0,"java.lang.String",{U:1,b:1,c:1,$:1,d:1,w:1},a=>"string"===typeof a);function Y(){}Y.prototype=new Ea;Y.prototype.constructor=Y;function Ga(){}Ga.prototype=Y.prototype;function Z(){}Z.prototype=new Ga;Z.prototype.constructor=Z;F(Z,"java.lang.JSConsoleBasedPrintStream",{fa:1,R:1,Q:1,G:1,E:1,H:1,F:1,W:1});h=new l(0,0);ka.D=h;G.k||(G.k=ja());new G.k.x([]);
try{ta()}catch(a){throw a;};
}).call(this);
//# sourceMappingURL=main.js.map
